//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2Cp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OUI_Non.StringsAr", typeof(StringsAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : الرجاء إدخال الإجابة الصحيحة.
        /// </summary>
        internal static string ans_txt {
            get {
                return ResourceManager.GetString("ans_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للتعديل.
        /// </summary>
        internal static string btn_modifier {
            get {
                return ResourceManager.GetString("btn_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string Btn_prece {
            get {
                return ResourceManager.GetString("Btn_prece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string btn_sauvgarder {
            get {
                return ResourceManager.GetString("btn_sauvgarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string Btn_suiv {
            get {
                return ResourceManager.GetString("Btn_suiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم : التناظر صحيح                                                                                                       .
        /// </summary>
        internal static string describtion_txt1 {
            get {
                return ResourceManager.GetString("describtion_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا : التناظر غير صحيح                                                                                                    .
        /// </summary>
        internal static string describtion_txt2 {
            get {
                return ResourceManager.GetString("describtion_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string non_txt {
            get {
                return ResourceManager.GetString("non_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        internal static string oui_txt {
            get {
                return ResourceManager.GetString("oui_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد المحاولة.
        /// </summary>
        internal static string retry_txt {
            get {
                return ResourceManager.GetString("retry_txt", resourceCulture);
            }
        }
    }
}
